### ISSUE TITLE
Setting up a template for icingaweb2/director not described

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#11]
Hi there,

I set up the proxy link for icingadirector as described in the manual and ran into this error:

D, [2017-05-23T13:10:32.498957 ] DEBUG -- : IcingaDirector: GET request to host?name=foreman_host
E, [2017-05-23T13:10:32.582021 ] ERROR -- : Template foreman_host not found.
D, [2017-05-23T13:10:32.582126 ] DEBUG -- : Template foreman_host not found. (RuntimeError)

Because there is no mention a template in icingaweb2/director should be created with the name foreman_host.

**Comment by dgoetz** [comment]
Added this to the Readme, will also create a feature request to foreman_monitoring to allow to set the default template name as a setting.
