### ISSUE TITLE
distinguish between user and passwords

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#12]
As far as I can see there are two users and passwords to be set in the configs on two systems, and in the README they are both

user = foreman
password = foreman

That's ok for testing purposes but for production purposes I'd like be able to distinguish between the two accounts and the passwords.

Could you change the README to reflect those different users and give them unique passwords, that will make the document much easier to parse. So I'd like to suggest something like:

user = foremanapi
password = apisecret

and

user = foremandirector
password = directorsecret

Thanks!

**Comment by dgoetz** [comment]
Thought quite a while about this and also asked some others about. Broad agreement was they use a user named foreman as Icinga 2 API user and Icinga Web 2 user as they only want to identify the use case of the user. Every one who wants to use different names and passwords (which is also not the preferred way as certificate based authentication for Icinga 2 and source-based autologin to Icinga Web 2 are more common) can do so. Also changing this in the Readme would make only sense if I do so in the example configuration and release a new package.

**Comment by hboetes** [comment]
ok, thanks for taking my request into consideration.
