### ISSUE TITLE
Add host creation

### ISSUE THREAD

**Issue by dgoetz** [theforeman/smart_proxy_monitoring#2]
Add host creation to the smart proxy so a host created in the Foreman GUI could automatically appear in monitoring.

**Comment by dgoetz** [comment]
Pushed an initial approach working for the Icinga 2 provider to the branch "features/host-creation".

A request to the smart proxy like the following will create a host:
`curl -k --cacert /var/lib/puppet/ssl/certs/ca.pem --cert /var/lib/puppet/ssl/certs/foreman-dev.localdomain.pem --key /var/lib/puppet/ssl/private_keys/foreman-dev.localdomain.pem -X POST "https://192.168.142.3:8443/monitoring/host/test.localdomain" -d 'attributes={"address": "127.0.0.2"}'`

**Comment by timogoebel** [comment]
Added in 7a4c3aff734c2f3b9fd133fadf88e9862955e, df84ba502d758f82c3ef76af5e2751ce670f82f7 and 349e1dc8494885ed043496c31ae0aef4ed4f4e35.
