### ISSUE TITLE
Changing icinga2 checks for nodes don´t effect monitoring proxy

### ISSUE THREAD

**Issue by elderorange** [theforeman/smart_proxy_monitoring#22]
Hi,

I created a node and added the load check to it on icinga2 server.
After removing the check it still stays on monitoring tab with status green OK.

Foreman: 1.19.0
monitoring-plugin: 1.0.1-1
icinga2: 2.9.1-1

**Comment by dgoetz** [comment]
Thanks for the report. It is more related to the GUI part where we have to solve this because there is no reliable information about removal of objects in Icinga to forward. We already have an issue for this so I close here in favor of https://github.com/theforeman/foreman_monitoring/issues/48.
