### ISSUE TITLE
documentation suggestions.

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#4]
- please add instructions on how to restart all foreman services in order to see the new module i.e.
  - service foreman-proxy restart; service foreman restart; service apache2 restart
- please add the useful logfiles to check for errors for instance:
  - /var/log/foreman-proxy/proxy.log
- Please move the yml files for https://github.com/theforeman/smart_proxy_monitoring to the top, even in a non functional state. They ensure people see what's happening and know what they are working on.

**Comment by hboetes** [comment]
Another one:
```
chown nagios /etc/icinga2/pki/
```
because of

```
# icinga2 pki new-cert --cn $(hostname -f) --key /etc/icinga2/pki/$(hostname -f).key --csr /etc/icinga2/pki/$(hostname -f).csr
information/base: Writing private key to '/etc/icinga2/pki/icinga01.foreman.key'.
critical/SSL: Error while opening private RSA key file '/etc/icinga2/pki/icinga01.foreman.key': 33558541, "error:0200100D:system library:fopen:Permission denied"
```

**Comment by dgoetz** [comment]
* For the daemons I only added foreman-proxy within here, but will this address in a separate patch for foreman_monitoring.
* I added a troubleshooting section including the logs.
* For moving the yml files I do not like to follow your suggestion as I think having it in the order you typically have to do the work is more useful. So configuring the monitoring solution first comes for connecting the Smart Proxy to it.
* I added a statement to address directory permissions and a possible solution using `install` which will work if directory is present or not.

Are you fine with this solution or do you complete disagree with me on some topics? Any other suggestion?

**Comment by hboetes** [comment]
Thank you for taking my points into consideration. The ordering of the document is a matter of taste I think. That shouldn't be too much of a deal.
