### ISSUE TITLE
denglisch

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#8]
I know you're not native english speakers — neither am I — I try to read through it, but some sentences are really hard to understand, for example:

> In addition you have to configure the provider Icingadirector for managing hosts in the Icinga Web 2 Module Director.

I tried really hard, but I can't be sure what you are trying to say here. And it is an important sentence.

**Comment by dgoetz** [comment]
I have no idea how to change the wording here, as I think the major problem here is the name "    Icinga Web 2 Module Director", so I added some further explanation which properly helps.
