### ISSUE TITLE
Failed to create a monitoring object lars.foreman: ERF12-6134 [ProxyAPI::ProxyException]: Unable to create monitoring host object for lars.foreman ([RestClient::NotFound]:                    404 Not Found) for proxy https://george.foreman:8443/monitoring

### ISSUE THREAD

**Issue by hboetes** [theforeman/smart_proxy_monitoring#9]
I already found the cause of this problem: I had a bad line in the foreman host template in icinga. So I would like to request a nicer message that explains the problem. This may very well be a bug in foreman-proxy which does not forward the properly. If so I wouldn't mind forwarding this problem to the foreman-proxy bug list.

**Comment by dgoetz** [comment]
I think this was addressed by @timogoebel in commit ade11a2

**Comment by hboetes** [comment]
It was indeed.
